name: x3d-tf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=py38h06a4308_0
  - aiohttp=3.6.3=py38h7b6447c_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=3.1.1=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - gast=0.3.3=py_0
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py38hf8bcb03_0
  - h5py=2.10.0=py38hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.2=py38_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - multidict=4.7.6=py38h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1h=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pip=20.2.4=py38h06a4308_0
  - protobuf=3.13.0.1=py38he6710b0_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h7579374_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - setuptools=50.3.1=py38h06a4308_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py38_1
  - tk=8.6.10=hbc83047_0
  - urllib3=1.25.11=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.2=py38h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - astroid==2.4.2
    - backcall==0.2.0
    - decorator==4.4.2
    - ipykernel==5.3.4
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - isort==5.6.4
    - jedi==0.17.2
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - keras-preprocessing==1.1.2
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - numpy==1.18.5
    - parso==0.7.1
    - pep8==1.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pygments==2.7.2
    - pylint==2.6.0
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - scipy==1.4.1
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - toml==0.10.2
    - tornado==6.1
    - traitlets==5.0.5
    - wcwidth==0.2.5
    - yacs==0.1.8
prefix: /home/fogidi/miniconda3/envs/x3d-tf
